### ISSUE TITLE
Edit Failure Question

### ISSUE THREAD

**Issue by yunchao-ding** [changwoonchoi/IBL-NeRF#10] opened 2023-03-21 09:31 UTC
Hi,
Why did I add a mask image to be edited in the test, but the generated image did not achieve the editing effect? The generated image only had an obvious mask image in the results "n_dot_v_000. png", "reflected_coarse_radiance_x_000. png", "reflected_radiance_000. png", "target_normal_map_000. png", but there was no editing success or trace of editing in "radiance_000. png", "rgb_000. png". The purpose of my preparation for editing was to roughen up the thick wall of the teapot in the kitchen scene to make it non reflective, but it seems to have failed.

**Comment by Pomelo-king** [comment] 2023-03-21 09:46
Did you fail to edit the mask map because you did not upload it correctly?

**Comment by Pomelo-king** [comment] 2023-03-21 09:47
However, I have a question about how to modify the roughness to achieve the editing effect in the paper?

**Comment by xcandxc** [comment] 2023-03-22 02:38
When I was editing, I only managed to achieve changes in reflectance intensity in the results, but I didn't achieve any changes in roughness, nor was I able to achieve the realistic effect mentioned in the paper, especially in editing the lampshade in the kitchen scene.

**Comment by Pomelo-king** [comment] 2023-03-22 02:59
I can retrieve the reflectance and roughness results, but I still couldn't reproduce the perfect results as shown in the paper.

**Comment by Pomelo-king** [comment] 2023-03-22 03:01
> Hi, Why did I add a mask image to be edited in the test, but the generated image did not achieve the editing effect? The generated image only had an obvious mask image in the results "n_dot_v_000. png", "reflected_coarse_radiance_x_000. png", "reflected_radiance_000. png", "target_normal_map_000. png", but there was no editing success or trace of editing in "radiance_000. png", "rgb_000. png". The purpose of my preparation for editing was to roughen up the thick wall of the teapot in the kitchen scene to make it non reflective, but it seems to have failed.
Is it possible that your image settings are incorrect? I also encountered the same issue before, but I eventually resolved it.

**Comment by yunchao-ding** [comment] 2023-03-22 06:46
Hi,
How did you modify the albedo to white, red, and green in your paper? At the same time, after modifying the roughness, the generated image looks very realistic. How is it set?

**Comment by yunchao-ding** [comment] 2023-03-22 07:03
No matter how the albedo and roughness parameters are set, the results do not change. Why is this?
Set the following parameters:
editing_ target_ albedo_ list = [0.1]
editing_ target_ roughness_ list = [1]

**Comment by yunchao-ding** [comment] 2023-03-23 13:21
![rgb_000](https://user-images.githubusercontent.com/112450228/227216203-9e794c36-7c23-41d7-b803-9c86b06f3743.png)
Hi,I still haven't been able to solve this problem, no matter what I do, I can't change the albedo and roughness of the target area, only get an image like this.Hope to get your advice!

**Comment by changwoonchoi** [comment] 2024-02-29 08:17
Sorry for very late reply..

As I mentioned my reply in #13 , we did not provide the example files for editing but you can freely edit whatever you want.
To @yunchao-ding, as @Pomelo-king is able to edit the scene, I'll close the issue.

Basically, to edit scenes or insert the object, all you need it the final pixel-wise values what you want to override!

**Closed as completed by changwoonchoi** 2024-02-29 08:17 UTC
